// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zldcvhxnjhgfbcozglgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZGN2aHhuamhnZmJjb3pnbGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDQ5NDcsImV4cCI6MjA2OTc4MDk0N30.uvWK16Lpk6xX1zUvWc6sZYshSbbvYj_5dKGqzqSAGOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});